### ISSUE TITLE
[General] Setup main layout

### ISSUE THREAD

**Issue by iiAbady** [202212-GIZ-YE-FEW/Web_Wizards_Pebble#11]
**Task title**
Setup main layout

**Task description**
Setup the main layout consisting of header and footer.

**Subtasks**
- [x] Add navbar
- [x] Add logo
- [x] Add signup and signin (unsigned)
- [ ] Add user icon (signed)
- [x] Add footer with links

**Screenshots**

![Image](https://user-images.githubusercontent.com/29796196/227804577-7df56a38-bea9-4653-a7cc-7585943ce3df.png)

![Image](https://user-images.githubusercontent.com/29796196/227804591-644d30de-eb56-4afa-a454-86506bf17845.png)

**Link to the component on Figma**
https://www.figma.com/file/IEhYhDLnrHmUuYercEZUjA/Pebble-work?node-id=1830-8562&t=T4zHEMAENyzMmQGs-4 (unsigned)
https://www.figma.com/file/IEhYhDLnrHmUuYercEZUjA/Pebble-work?node-id=1830-8462&t=T4zHEMAENyzMmQGs-4 (signed)
https://www.figma.com/file/IEhYhDLnrHmUuYercEZUjA/Pebble-work?node-id=1830-7131&t=T4zHEMAENyzMmQGs-4 (footer)
