### ISSUE TITLE
[Events Page] Add aside filters

### ISSUE THREAD

**Issue by iiAbady** [202212-GIZ-YE-FEW/Web_Wizards_Pebble#15]
**Task title**
Add aside filters

**Task description**
Add event aside filters which include calendar, week, location, interest, 

**Subtasks**
- [x] Add calendar filter
- [x] Add week filter
- [x] Add location filter
- [x] Add interset filter
- [x] Add interests component
 
**Screenshots**

![Image](https://user-images.githubusercontent.com/29796196/227805279-9f17cf8a-cbd4-47f9-8698-32b17246c4d2.png)

**Link to the component on Figma**
https://www.figma.com/file/IEhYhDLnrHmUuYercEZUjA/Pebble-work?node-id=1831-20506&t=T4zHEMAENyzMmQGs-4 (Calendar)
