### ISSUE TITLE
[Sign up] Add sign up fields components.

### ISSUE THREAD

**Issue by iiAbady** [202212-GIZ-YE-FEW/Web_Wizards_Pebble#16]
**Task title**
Add sign up fields components.

**Task description**
Add sign up name, surname, email address, password component.

**Subtasks**

- [x] Add name field
- [x] Add surname field
- [x] Add email field
- [x] Add password field
- [x] Add have an account? section
- [x] Add button

**Screenshots**

![Image](https://user-images.githubusercontent.com/29796196/227806304-0e78642c-7f53-46e2-8252-1d272e6e6e9d.png)

**Link to the component on Figma**
https://www.figma.com/file/IEhYhDLnrHmUuYercEZUjA/Pebble-work?node-id=1719-3668&t=T4zHEMAENyzMmQGs-4
