### ISSUE TITLE
[Event Page] Add header

### ISSUE THREAD

**Issue by iiAbady** [202212-GIZ-YE-FEW/Web_Wizards_Pebble#21]
**Task title**
Add header

**Task description**
Add event header with its image, attendees, location , time, and organizer.

**Subtasks**
- [x] Add image
- [x] Add attendees component
- [x] Add location component
- [x] Add time component
- [x] Add orgainzer component

**Screenshots**

![Image](https://user-images.githubusercontent.com/29796196/227806951-baa177a0-d948-42ef-91b7-d625f607374f.png)

**Link to the component on Figma**
https://www.figma.com/file/IEhYhDLnrHmUuYercEZUjA/Pebble-work?node-id=1665-2647&t=T4zHEMAENyzMmQGs-4

**Comment by sulmi24** [comment]
Hi  @iiAbady 
Thank you for assigning me the task! I'm excited to work on it and will make sure to complete each subtask to the best of my ability. I'll also make sure to update the task status as I complete each subtask, so we can keep track of progress.
