### ISSUE TITLE
[Edit Profile Page] Add change password component.

### ISSUE THREAD

**Issue by iiAbady** [202212-GIZ-YE-FEW/Web_Wizards_Pebble#28]
**Task title**
Add change password component.

**Task description**
Add change password component to the edit profile page with password and the save button. (no functionality is required for now)

**Subtasks**
- [x] Add password component
- [x] Add save button
- [x] Add cacnel button

**Screenshots**

![Image](https://user-images.githubusercontent.com/29796196/228017820-ece0b1b2-13fa-4ef7-94dd-8f917e6e418f.png)

**Link to the component on Figma**
https://www.figma.com/file/IEhYhDLnrHmUuYercEZUjA/Pebble-work?node-id=1794-4900&t=kAS5jf3gsspDpoKH-4
