### ISSUE TITLE
Develop Sign-in Authentication Field

### ISSUE THREAD

**Issue by SufyanCS** [202212-GIZ-YE-FEW/Web_Wizards_Pebble#67]
**Task title**
Develop Sign-in Authentication Field

**Task description**
The current app does not have a sign-in authentication field. This task involves developing a sign-in authentication field that allows users to sign in to the app with their email and password.

**Subtasks**

- [ ] Create Sign-in Form with Firebase Authentication API
- [ ] Validate user input and show error messages if the input is invalid
- [ ] Authenticate user credentials against a Firebase backend
- [ ] Redirect users to the Events page after successful authentication

**Screenshots**
![Signin](https://user-images.githubusercontent.com/119085953/230812964-68d42607-72a5-444d-952c-aa8af992dd6b.png)

**Link to the component on Figma**
[Component Link](https://www.figma.com/file/IEhYhDLnrHmUuYercEZUjA/Pebble-work?node-id=1719%3A3587&t=s755vwSivf94F1vs-1)
