### ISSUE TITLE
Develop Sign-up Authentication Field

### ISSUE THREAD

**Issue by SufyanCS** [202212-GIZ-YE-FEW/Web_Wizards_Pebble#68]
**Task title**
Develop Sign-up Authentication Field

**Task description**
The current app does not have a sign-up authentication field. This task involves developing a sign-up authentication field that allows users to create an account in the app with their Name, Surname, Email and password.

**Subtasks**

- [ ] Allow users to enter their Name, SurName, Email and Password to create an account
- [ ] Validate user input and show error messages if the input is invalid or already exists
- [ ] Authenticate user credentials against a Firebase backend
- [ ] After successful Sign-up, redirect users to the Edit Profile page where they can choose their interests

**Screenshots**
![signup](https://user-images.githubusercontent.com/119085953/230814813-904eadca-aaa4-4377-9f93-dd263f97ad09.png)

**Link to the component on Figma**
[Component Link](https://www.figma.com/file/IEhYhDLnrHmUuYercEZUjA/Pebble-work?node-id=1719%3A3667&t=s755vwSivf94F1vs-1)
